title: "Tutorials"
description: "Tutorials for people interested in population genomics"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jemoji

just_the_docs:
  search_enabled: true
  heading_anchors: true
