title: "Tutorials"
description: "Tutorials for people interested in population genomics"

# Use the Just the Docs theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable emoji support
gems:
  - jemoji

# Build settings for Just the Docs
just_the_docs:
  search_enabled: true
  heading_anchors: true
